### ISSUE TITLE
[Bug]:  Button is not working

### ISSUE THREAD

**Issue by mukilan2815** [CodeHarborHub/codeharborhub#291] opened 2024-05-30 02:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are two buttons Get started and Courses. but When i press those button it is not navigating , i need to press those words to get navigated. This makes user experience down. I can fix this issue. 

### Expected behavior

When user presses that button it should navigate. 

### Add ScreenShots

![image_2024-05-30_075852821](https://github.com/CodeHarborHub/codeharborhub/assets/71129858/e8c157e2-a039-4d9a-a8bd-af2f66ca46c4)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ajay-Dhangar** [comment] 2024-05-30 04:03
Yes, you can try it. However, please note that clicking directly on the button's text works as intended. This is not a bug. If you have any other ideas or suggestions, please share them with us, and we can work on them together.

**Comment by mukilan2815** [comment] 2024-05-30 05:43
I will add Node js in the tutorial section and i will make those card size in loved by many users section , card size as fixed so that it will be evenly aligned and add neumorphism effect there.


![image_2024-05-30_111106348](https://github.com/CodeHarborHub/codeharborhub/assets/71129858/ab9f14e2-f1ef-42dd-b6cd-5ae98b053946)

**Comment by Ajay-Dhangar** [comment] 2024-05-30 07:34
okay, work on node.js tutorial and create new issue and close it.

**Closed** 2024-05-30 09:20 UTC
Labels: bug
